import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { readFileSync } from "node:fs";
import { test } from "node:test";

test("V2 workflow docs and adapters expose content quality flow", () => {
  const workflow = readFileSync("workflows/19-v2-content-quality.md", "utf8");
  const clusterWorkflow = readFileSync("workflows/13-cluster-strategy.md", "utf8");
  const readme = readFileSync("README.md", "utf8");
  const agent = readFileSync("AGENT.md", "utf8");
  const gemini = readFileSync("adapters/gemini-cli/GEMINI.md", "utf8");
  const pageCommand = readFileSync("adapters/gemini-cli/commands/seo/page.toml", "utf8");
  const helpCommand = readFileSync("adapters/gemini-cli/commands/seo/help.toml", "utf8");
  const codexSkill = readFileSync("adapters/codex/skills/seo-page-creator/SKILL.md", "utf8");
  const antigravity = readFileSync("adapters/antigravity/AGENTS.md", "utf8");

  assert.match(workflow, /SERP Research Ledger Gate/);
  assert.match(workflow, /Social\/Video Research Gate/);
  assert.match(workflow, /Narrative Brief Gate/);
  assert.match(workflow, /Human Editorial Brief/);
  assert.match(workflow, /Claim-First Section Plan/);
  assert.match(workflow, /Page Depth Contract/);
  assert.match(workflow, /validate-depth/);
  assert.match(workflow, /final-copy-draft\.json/);
  assert.match(workflow, /The deterministic CLI does not write V2\.1 final prose/);
  assert.match(workflow, /pageStructure\.intentPattern/);
  assert.match(workflow, /pageStructure\.structureVariant/);
  assert.match(workflow, /not globally fixed across all page types/);
  assert.match(workflow, /pre-draft-quality-brief\.json/);
  assert.match(workflow, /anti-thin-page gate/);
  assert.match(workflow, /Publish-Worthiness Gate/);
  assert.match(workflow, /SERP Superiority Gate/);
  assert.match(workflow, /Research-Derived Structure Gate/);
  assert.match(workflow, /researchDerivedStructurePlan/);
  assert.match(workflow, /structurePlanDeliveryProof/);
  assert.match(workflow, /first 3 visible sections/);
  assert.match(workflow, /Primary keyword top 5 SERP pages/);
  assert.match(workflow, /Secondary keyword or long-tail top 3 SERP pages/);
  assert.match(workflow, /top 4 main intent dimensions/);
  assert.match(workflow, /required superiority component/);
  assert.match(workflow, /5 differentiated improvements/);
  assert.match(workflow, /whyThisDeservesToRank/);
  assert.match(workflow, /superiorityProof/);
  assert.match(workflow, /Visible citation\/source handling/);
  assert.match(workflow, /recommendation sanity/);
  assert.match(workflow, /troubleshooting plan/);
  assert.match(workflow, /sourceRefs/);
  assert.match(workflow, /mappedSectionId/);
  assert.match(workflow, /finalCopyUse/);
  assert.match(workflow, /Top 10 meaningful SERP body extractions/);
  assert.match(workflow, /content_ready/);
  assert.match(workflow, /publish_ready/);

  assert.match(readme, /seo-agent v2 prepare-page/);
  assert.match(readme, /seo-agent v2 validate-depth/);
  assert.match(readme, /final-copy-draft\.json/);
  assert.match(readme, /Intent-Aware Page Structure/);
  assert.match(readme, /sectionIntent/);
  assert.match(readme, /evidenceBudget/);
  assert.match(readme, /pre-draft-quality-brief\.json/);
  assert.match(readme, /publish-worthiness/);
  assert.match(readme, /SERP Superiority Gate/);
  assert.match(readme, /Research-Derived Structure Gate/);
  assert.match(readme, /researchDerivedStructurePlan/);
  assert.match(readme, /structurePlanDeliveryProof/);
  assert.match(readme, /primary keyword top 5 SERP pages/);
  assert.match(readme, /secondary keyword or long-tail top 3 SERP set/);
  assert.match(readme, /top 4 intent dimensions/);
  assert.match(readme, /required superiority component/);
  assert.match(readme, /5 differentiated visible improvements/);
  assert.match(readme, /superiorityProof/);
  assert.match(readme, /whyThisDeservesToRank/);
  assert.match(readme, /sourceRefs/);
  assert.match(readme, /unfocused and long-tail/);
  assert.match(readme, /final page packet, editorial QA report, and image manifest/);
  assert.match(readme, /run-ledger\.jsonl/);
  assert.match(readme, /current-page\.lock/);
  assert.match(readme, /Content and structure uniqueness are required across the batch and across historical runs/);
  assert.match(readme, /shared HTML body template/);
  assert.match(readme, /same body section pattern/);
  assert.match(readme, /SERP, PAA, Reddit\/forum\/video, AI Overview, audience-language, and competitor-gap research/);

  assert.match(agent, /workflows\/19-v2-content-quality\.md/);
  assert.match(agent, /No hard-gate override/);

  assert.doesNotMatch(gemini, /\/seo:v2/);
  assert.match(gemini, /\/seo:page now uses V2\.1 quality gates/);
  assert.equal(existsSync("adapters/gemini-cli/commands/seo/v2.toml"), false);
  assert.match(pageCommand, /Generate one V2 content-quality page workflow/);
  assert.doesNotMatch(pageCommand, /\/seo:v2/);
  assert.match(pageCommand, /human-editorial-brief/);
  assert.match(pageCommand, /claim-first-section-plan/);
  assert.match(pageCommand, /pageStructure\.intentPattern/);
  assert.match(pageCommand, /S3_context or S4_main_content/);
  assert.match(pageCommand, /pre-draft-quality-brief\.json/);
  assert.match(pageCommand, /publish-worthiness/);
  assert.match(pageCommand, /SERP Superiority/);
  assert.match(pageCommand, /Research-Derived Structure/);
  assert.match(pageCommand, /researchDerivedStructurePlan/);
  assert.match(pageCommand, /structurePlanDeliveryProof/);
  assert.match(pageCommand, /primary keyword top 5 competitors/);
  assert.match(pageCommand, /secondary keyword or long-tail variant/);
  assert.match(pageCommand, /top 4 intent dimensions/);
  assert.match(pageCommand, /1 custom superiority component/);
  assert.match(pageCommand, /5 differentiated visible improvements/);
  assert.match(pageCommand, /superiorityProof/);
  assert.match(pageCommand, /whyThisDeservesToRank/);
  assert.match(pageCommand, /sourceRefs/);
  assert.match(pageCommand, /validate-human/);
  assert.match(pageCommand, /validate-gates/);
  assert.match(pageCommand, /validate-depth/);
  assert.match(pageCommand, /final-copy-draft\.json/);

  assert.match(codexSkill, /V2 Content Quality/);
  assert.match(codexSkill, /validate-depth/);
  assert.match(codexSkill, /final-copy-draft\.json/);
  assert.match(codexSkill, /pageStructure\.intentPattern/);
  assert.match(codexSkill, /evidenceBudget/);
  assert.match(codexSkill, /pre-draft-quality-brief\.json/);
  assert.match(codexSkill, /publish-worthiness/);
  assert.match(codexSkill, /SERP Superiority/);
  assert.match(codexSkill, /Research-Derived Structure/);
  assert.match(codexSkill, /researchDerivedStructurePlan/);
  assert.match(codexSkill, /structurePlanDeliveryProof/);
  assert.match(codexSkill, /primary keyword top 5 SERP competitors/);
  assert.match(codexSkill, /top 3 pages for at least one secondary keyword/);
  assert.match(codexSkill, /top 4 intent dimensions/);
  assert.match(codexSkill, /research-custom superiority component/);
  assert.match(codexSkill, /5 differentiated visible improvements/);
  assert.match(codexSkill, /superiorityProof/);
  assert.match(codexSkill, /whyThisDeservesToRank/);
  assert.match(codexSkill, /sourceRefs/);
  assert.match(codexSkill, /unfocused and long-tail/);
  assert.match(codexSkill, /current-page\.lock/);
  assert.match(codexSkill, /debug-bundle/);
  assert.match(codexSkill, /historical pages from previous runs/);
  assert.match(codexSkill, /shared body section patterns are forbidden/i);
  assert.match(codexSkill, /CTA placement, and CTA body must be page-specific and research-derived/);
  assert.match(gemini, /validate-depth/);
  assert.match(gemini, /final-copy-draft\.json/);
  assert.match(gemini, /pageStructure\.structureVariant/);
  assert.match(gemini, /S3_context/);
  assert.match(gemini, /pre-draft-quality-brief\.json/);
  assert.match(gemini, /publish-worthiness/);
  assert.match(gemini, /SERP Superiority/);
  assert.match(gemini, /Research-Derived Structure/);
  assert.match(gemini, /researchDerivedStructurePlan/);
  assert.match(gemini, /structurePlanDeliveryProof/);
  assert.match(gemini, /primary keyword top 5 SERP competitors/);
  assert.match(gemini, /top 3 pages for at least one secondary keyword/);
  assert.match(gemini, /top 4 intent dimensions/);
  assert.match(gemini, /research-custom superiority component/);
  assert.match(gemini, /5 differentiated visible improvements/);
  assert.match(gemini, /superiorityProof/);
  assert.match(gemini, /whyThisDeservesToRank/);
  assert.match(gemini, /sourceRefs/);
  assert.match(gemini, /unfocused and long-tail/);
  assert.match(gemini, /run-ledger\.jsonl/);
  assert.match(gemini, /current-page\.lock/);
  assert.match(gemini, /historical pages from previous runs/);
  assert.match(gemini, /shared body section patterns are forbidden/i);
  assert.match(gemini, /CTA placement, and CTA body copy must be distinct/);

  assert.match(antigravity, /Antigravity Adapter/);
  assert.match(antigravity, /AGENT\.md/);
  assert.match(antigravity, /README\.md/);
  assert.match(antigravity, /workflows\/19-v2-content-quality\.md/);
  assert.match(antigravity, /adapters\/codex\/skills\/seo-page-creator\/SKILL\.md/);
  assert.match(antigravity, /adapters\/gemini-cli\/GEMINI\.md/);
  assert.match(antigravity, /V2\.1/);
  assert.match(antigravity, /validate-human/);
  assert.match(antigravity, /validate-gates/);
  assert.match(antigravity, /validate-depth/);
  assert.match(antigravity, /final-copy-draft\.json/);
  assert.match(antigravity, /pageStructure\.sections/);
  assert.match(antigravity, /evidenceNeeded/);
  assert.match(antigravity, /pre-draft-quality-brief\.json/);
  assert.match(antigravity, /publish-worthiness/);
  assert.match(antigravity, /SERP Superiority/);
  assert.match(antigravity, /Research-Derived Structure/);
  assert.match(antigravity, /researchDerivedStructurePlan/);
  assert.match(antigravity, /structurePlanDeliveryProof/);
  assert.match(antigravity, /primary keyword top 5 competitors/);
  assert.match(antigravity, /top 3 pages for at least one secondary keyword/);
  assert.match(antigravity, /top 4 intent dimensions/);
  assert.match(antigravity, /1 custom superiority component/);
  assert.match(antigravity, /5 differentiated visible improvements/);
  assert.match(antigravity, /superiorityProof/);
  assert.match(antigravity, /whyThisDeservesToRank/);
  assert.match(antigravity, /sourceRefs/);
  assert.match(antigravity, /unfocused and long-tail/);
  assert.match(antigravity, /final copy, page packet, image manifest, commit, push, deploy, or publish until `validate-human`, `validate-gates`, and `validate-depth` pass/);
  assert.match(antigravity, /final page packet, editorial QA report, and image manifest/);
  assert.match(antigravity, /current-page\.lock/);
  assert.match(antigravity, /run-ledger\.jsonl/);
  assert.match(antigravity, /Do not batch by workflow stage/);
  assert.match(antigravity, /historical pages from previous runs/);
  assert.match(antigravity, /shared body section patterns are forbidden/i);
  assert.match(antigravity, /CTA placement, and CTA body must be page-specific and research-derived/);
  assert.match(antigravity, /future-page research, copy, images, assets, page packets, QA, commits, deploys, or manifests/);
  assert.match(antigravity, /commit, push\/deploy, and verify HTTP 200 OK/);
  assert.match(antigravity, /Only after the current page is live or terminally skipped may you select the next page/);

  for (const doc of [clusterWorkflow, agent, readme, workflow, codexSkill, gemini, pageCommand, helpCommand, antigravity]) {
    assert.match(doc, /Step 0A|0A/);
    assert.match(doc, /Step 0A Foundation|Foundation gate|foundation gate|foundation verdict|foundationVerdict/);
    assert.match(doc, /selectedTopic/);
    assert.match(doc, /topicBoundarySummary/);
    assert.match(doc, /businessSideRelevance/);
    assert.match(doc, /primarySearchProblem/);
    assert.match(doc, /wrongPageRisk/);
    assert.match(doc, /desiredOutcome/);
    assert.match(doc, /readerState/);
    assert.match(doc, /problemLanguage|problem-language/);
    assert.match(doc, /cleanedPhrase/);
    assert.match(doc, /sourceClass/);
    assert.match(doc, /search_surface/);
    assert.match(doc, /audience_language/);
    assert.match(doc, /relationshipCheck/);
    assert.match(doc, /foundationVerdict/);
    assert.match(doc, /mustCarryForward/);
    assert.match(doc, /6\/8 phrases|6\/8/);
    assert.match(doc, /business relevance is unclear|Business relevance is unclear/);
  }

  for (const doc of [clusterWorkflow, codexSkill, gemini, pageCommand, helpCommand, antigravity]) {
    assert.match(doc, /Step 0B|0B/);
    assert.match(doc, /Page Scope Contract|PageScopeContract/);
    assert.match(doc, /targetKeyword/);
    assert.match(doc, /targetQueryIntent/);
    assert.match(doc, /contractHash/);
    assert.match(doc, /mustCover/);
    assert.match(doc, /mustNotCover/);
    assert.match(doc, /pageScopeSummary/);
    assert.match(doc, /uniqueContribution/);
    assert.match(doc, /live keyword\/search evidence|live evidence|live keyword\/search/);
    assert.match(doc, /light SERP overlap/);
    assert.match(doc, /batch duplicate check|duplicate check/);
    assert.match(doc, /No downstream work may start|no downstream work may start|Downstream workflows must not start|before any downstream|before downstream|before page generation/);
  }

  for (const doc of [clusterWorkflow, agent, readme, workflow, codexSkill, gemini, pageCommand, helpCommand, antigravity]) {
    assert.match(doc, /Step 1|Page Job Contract/);
    assert.match(doc, /pageJobContract/);
    assert.match(doc, /step0BContractHash/);
    assert.match(doc, /pageJobHash/);
    assert.match(doc, /pageJobStatement/);
    assert.match(doc, /audienceSentence/);
    assert.match(doc, /primaryHelpFormat/);
    assert.match(doc, /secondaryHelpFormats/);
    assert.match(doc, /primaryBusinessRole/);
    assert.match(doc, /riskLevel/);
    assert.match(doc, /claimSensitivity/);
    assert.match(doc, /taskConstraints/);
    assert.match(doc, /successCriteria/);
    assert.match(doc, /nonGoals/);
    assert.match(doc, /outcomeConsequence/);
    assert.match(doc, /evidenceBasis/);
    assert.match(doc, /jobUniquenessCheck/);
    assert.match(doc, /pageJobVerdict/);
    assert.match(doc, /inferenceRepairLog/);
    assert.match(doc, /return_to_0B/);
    assert.match(doc, /return_to_step1/);
  }

  for (const doc of [clusterWorkflow, agent, readme, workflow, codexSkill, gemini, pageCommand, helpCommand, antigravity]) {
    assert.match(doc, /Step 2|Search Intent Contract/);
    assert.match(doc, /searchIntentContract/);
    assert.match(doc, /searchIntentHash/);
    assert.match(doc, /intentStatement/);
    assert.match(doc, /dominantBroadIntent/);
    assert.match(doc, /coPrimaryBroadIntent/);
    assert.match(doc, /primaryDeeperIntent/);
    assert.match(doc, /projectSpecificIntentLabel/);
    assert.match(doc, /depthLevel/);
    assert.match(doc, /depthStyle/);
    assert.match(doc, /satisfactionCondition/);
    assert.match(doc, /tooShallowIf/);
    assert.match(doc, /wrongPageIf/);
    assert.match(doc, /recommendedPageType/);
    assert.match(doc, /dominantInternalContentFormat/);
    assert.match(doc, /supportingContentFormats/);
    assert.match(doc, /lightSerpValidation/);
    assert.match(doc, /top 5 SERP|top five SERP/i);
    assert.match(doc, /3\/5/);
    assert.match(doc, /mixedIntentHandling/);
    assert.match(doc, /adjacent/);
    assert.match(doc, /conflicting/);
    assert.match(doc, /pageJobAlignmentCheck/);
    assert.match(doc, /validatedIntentDecision/);
    assert.match(doc, /confirm/);
    assert.match(doc, /refine/);
    assert.match(doc, /correct/);
    assert.match(doc, /marketContextCheck/);
    assert.match(doc, /aiOverviewIntentSignal/);
    assert.match(doc, /intentVerdict/);
    assert.match(doc, /intentRepairLog/);
    assert.match(doc, /continue_to_prewriting/);
    assert.match(doc, /skip_page/);
  }

  for (const doc of [clusterWorkflow, agent, readme, workflow, codexSkill, gemini, pageCommand, helpCommand, antigravity]) {
    assert.match(doc, /Step 3|Page Format Contract/);
    assert.match(doc, /pageFormatContract/);
    assert.match(doc, /pageFormatHash/);
    assert.match(doc, /primaryPageType/);
    assert.match(doc, /secondaryPageTypeInfluences/);
    assert.match(doc, /primaryInternalContentFormat/);
    assert.match(doc, /supportingFormatInfluences/);
    assert.match(doc, /supportingContentElements/);
    assert.match(doc, /allowedScope/);
    assert.match(doc, /notAllowedScope/);
    assert.match(doc, /adjacentNeedRouting/);
    assert.match(doc, /rejectedPageTypes/);
    assert.match(doc, /rejectedInternalFormats/);
    assert.match(doc, /formatDecisionStatement/);
    assert.match(doc, /step2RecommendationFit/);
    assert.match(doc, /formatEvidenceBasis/);
    assert.match(doc, /scopeBoundaryCheck/);
    assert.match(doc, /formatCompatibilityCheck/);
    assert.match(doc, /formatRiskCheck/);
    assert.match(doc, /formatUniquenessCheck/);
    assert.match(doc, /businessConnectionBoundary/);
    assert.match(doc, /step3OutputMustNotContain/);
    assert.match(doc, /formatRepairLog/);
    assert.match(doc, /formatVerdict/);
    assert.match(doc, /return_to_step2/);
    assert.match(doc, /continue_to_prewriting/);
  }

  for (const doc of [clusterWorkflow, agent, readme, workflow, codexSkill, gemini, pageCommand, helpCommand, antigravity]) {
    assert.match(doc, /Step 4|Next Action Contract/);
    assert.match(doc, /nextActionContract/);
    assert.match(doc, /nextActionHash/);
    assert.match(doc, /userJourneyStage/);
    assert.match(doc, /secondaryJourneyStages/);
    assert.match(doc, /secondaryStageNotes/);
    assert.match(doc, /learning/);
    assert.match(doc, /evaluation/);
    assert.match(doc, /action/);
    assert.match(doc, /primaryNextAction/);
    assert.match(doc, /secondaryNextActions/);
    assert.match(doc, /ctaStrength/);
    assert.match(doc, /ctaStrengthMapping/);
    assert.match(doc, /ctaStrengthExceptionReason/);
    assert.match(doc, /ctaStrengthExceptionEvidenceRefs/);
    assert.match(doc, /soft/);
    assert.match(doc, /medium/);
    assert.match(doc, /direct/);
    assert.match(doc, /finalCopyGuidance/);
    assert.match(doc, /internalJourneyPath/);
    assert.match(doc, /nextActionStatement/);
    assert.match(doc, /stageEvidenceBasis/);
    assert.match(doc, /nextActionEvidenceBasis/);
    assert.match(doc, /step4InputFit/);
    assert.match(doc, /formatBoundaryCheck/);
    assert.match(doc, /businessRoleBoundaryCheck/);
    assert.match(doc, /brandConnectionFit/);
    assert.match(doc, /direct_business_connection/);
    assert.match(doc, /soft_brand_bridge/);
    assert.match(doc, /authority_building_internal_education/);
    assert.match(doc, /no_brand_connection_reader_first_justified/);
    assert.match(doc, /sensitiveActionRiskCheck/);
    assert.match(doc, /internalDestinationCheck/);
    assert.match(doc, /existing_internal_destination/);
    assert.match(doc, /missing_but_recommended/);
    assert.match(doc, /external_destination/);
    assert.match(doc, /ask_user_required/);
    assert.match(doc, /rejectedNextActions/);
    assert.match(doc, /nextActionUniquenessCheck/);
    assert.match(doc, /step4OutputMustNotContain/);
    assert.match(doc, /nextActionRepairLog/);
    assert.match(doc, /nextActionVerdict/);
    assert.match(doc, /nextActionDeliveryProof/);
    assert.match(doc, /return_to_step3/);
    assert.match(doc, /continue_to_prewriting/);
  }

  for (const doc of [clusterWorkflow, agent, readme, workflow, codexSkill, gemini, pageCommand, helpCommand, antigravity]) {
    assert.match(doc, /Step 5|SERP Competitor Analysis/);
    assert.match(doc, /serpCompetitorAnalysis/);
    assert.match(doc, /serpCompetitorHash/);
    assert.match(doc, /serp-competitor-analysis\.json/);
    assert.match(doc, /serp-competitor-analysis\.md/);
    assert.match(doc, /serpContext/);
    assert.match(doc, /sourceRegistry/);
    assert.match(doc, /primarySerpResults/);
    assert.match(doc, /reviewedCompetitors/);
    assert.match(doc, /supportingQuerySerpChecks/);
    assert.match(doc, /serpFeatureInventory/);
    assert.match(doc, /marketSerpFitCheck/);
    assert.match(doc, /deviceSerpCheck/);
    assert.match(doc, /mobileFirstSerpInterpretation/);
    assert.match(doc, /globalBenchmarkRelevanceCheck/);
    assert.match(doc, /indiaGlobalInfluenceBoundary/);
    assert.match(doc, /serpCannibalizationCheck/);
    assert.match(doc, /differentiationRequirement/);
    assert.match(doc, /commercialSerpSignals/);
    assert.match(doc, /serpQuestionAndRelatedSignals/);
    assert.match(doc, /serpStrengthLabel/);
    assert.match(doc, /minimumBarToMatch/);
    assert.match(doc, /opportunityGapsToExplore/);
    assert.match(doc, /coveragePatterns/);
    assert.match(doc, /contentAnglePatterns/);
    assert.match(doc, /depthBenchmark/);
    assert.match(doc, /trustSignalBenchmark/);
    assert.match(doc, /uxComponentBenchmark/);
    assert.match(doc, /competitorStrengthsToRespect/);
    assert.match(doc, /competitorWeaknessesAndGaps/);
    assert.match(doc, /serpInformedScopeProtection/);
    assert.match(doc, /directionValidation/);
    assert.match(doc, /competitorImitationRisk/);
    assert.match(doc, /analysisConfidence/);
    assert.match(doc, /batchSerpIsolationCheck/);
    assert.match(doc, /step5CompletenessChecklist/);
    assert.match(doc, /serpCompetitorSummaryStatement/);
    assert.match(doc, /serpCompetitorVerdict/);
    assert.match(doc, /continue_to_step6/);
    assert.match(doc, /top 10 organic|primary top 10/i);
    assert.match(doc, /top 5 direct|top 5 organic|top five organic/i);
    assert.match(doc, /at least 3 direct/i);
    assert.match(doc, /global benchmarks?/i);
    assert.match(doc, /AI Overview/);
    assert.match(doc, /copied competitor material|copy-like competitor material|copied competitor headings/);
    assert.match(doc, /serpCompetitorDeliveryProof/);
    assert.match(doc, /differentiationDeliveryProof/);
  }

  for (const doc of [clusterWorkflow, agent, readme, workflow, codexSkill, gemini, pageCommand, helpCommand, antigravity]) {
    assert.match(doc, /Step 6|Topic Research Bank/);
    assert.match(doc, /topicResearchBank/);
    assert.match(doc, /topicResearchHash/);
    assert.match(doc, /topic-research-bank\.json/);
    assert.match(doc, /topic-research-bank\.md/);
    assert.match(doc, /researchDepthDecision/);
    assert.match(doc, /researchAgenda/);
    assert.match(doc, /sourceRegistry/);
    assert.match(doc, /topicEvidenceSources/);
    assert.match(doc, /audienceSearchLanguageSources/);
    assert.match(doc, /extractedFacts/);
    assert.match(doc, /agendaCoverage/);
    assert.match(doc, /step5CarryForwardCoverage/);
    assert.match(doc, /researchBank/);
    assert.match(doc, /sourceConflictNotes/);
    assert.match(doc, /researchGaps/);
    assert.match(doc, /doNotUse/);
    assert.match(doc, /researchCompletenessChecklist/);
    assert.match(doc, /researchSummaryStatement/);
    assert.match(doc, /topicResearchVerdict/);
    assert.match(doc, /continue_to_step7/);
    assert.match(doc, /local-market evidence|localMarketEvidenceChecked|local-market/i);
    assert.match(doc, /not_allowed_for_claims|audience\/search-language|audience-search/i);
    assert.match(doc, /copied source|copied-looking|copied source material|copied source or competitor material/i);
    assert.match(doc, /topicResearchDeliveryProof/);
  }

  assert.equal(existsSync("docs/superpowers/specs/2026-07-11-step-5-serp-competitor-analysis-design.md"), true);
  assert.equal(existsSync("docs/superpowers/specs/2026-07-11-step-6-topic-research-bank-design.md"), true);
});
